
version: '3'

services:
  checkyBK:
    depends_on:
      - db
    build: 
      context: .
      dockerfile: Dockerfile
    image: checkyBK-docker
    container_name: checkyBK
    restart: always # reiniciar el contenedor si se detiene
    ports:
      - "${PORT}:${PORT}"
    # working_dir: /var/www/pokedex
    environment:
      MONGODB: ${MONGODB}
      PORT: ${PORT}
      DEFAULT_LIMIT: ${DEFAULT_LIMIT}
    # volumes:
    #   - ./:/var/www/pokedex

  db:
    image: mongo:7
    container_name: checkyBK
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: nest-checky
    volumes:
      - ./mongo:/data/db