version: '3'

services:
  checkyBK:
    build: 
      context: .
      dockerfile: Dockerfile
    image: checkyBK-docker
    container_name: checkyBK
    restart: always # reiniciar el contenedor si se detiene
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    # working_dir: /var/www/pokedex
    environment:
      MONGODB: ${MONGODB}
      PORT: ${PORT:-3000}
      DEFAULT_LIMIT: ${DEFAULT_LIMIT}
    # volumes:
    #   - ./:/var/www/pokedex