export type CatalogOption = { id: string; label: string };

/** Catálogo de ciudades — 32 capitales departamentales de Colombia + "Otra".
 *  Alineado con webapp `companyCities.config.ts`. */
export const COMPANY_CITIES_CATALOG: CatalogOption[] = [
  { id: 'arauca', label: 'Arauca' },
  { id: 'armenia', label: 'Armenia' },
  { id: 'barranquilla', label: 'Barranquilla' },
  { id: 'bogota', label: 'Bogotá' },
  { id: 'bucaramanga', label: 'Bucaramanga' },
  { id: 'cali', label: 'Cali' },
  { id: 'cartagena', label: 'Cartagena' },
  { id: 'cucuta', label: 'Cúcuta' },
  { id: 'florencia', label: 'Florencia' },
  { id: 'ibague', label: 'Ibagué' },
  { id: 'inirida', label: 'Inírida' },
  { id: 'leticia', label: 'Leticia' },
  { id: 'manizales', label: 'Manizales' },
  { id: 'medellin', label: 'Medellín' },
  { id: 'mitu', label: 'Mitú' },
  { id: 'mocoa', label: 'Mocoa' },
  { id: 'monteria', label: 'Montería' },
  { id: 'neiva', label: 'Neiva' },
  { id: 'pasto', label: 'Pasto' },
  { id: 'pereira', label: 'Pereira' },
  { id: 'popayan', label: 'Popayán' },
  { id: 'puerto_carreno', label: 'Puerto Carreño' },
  { id: 'quibdo', label: 'Quibdó' },
  { id: 'riohacha', label: 'Riohacha' },
  { id: 'san_andres', label: 'San Andrés' },
  { id: 'san_jose_del_guaviare', label: 'San José del Guaviare' },
  { id: 'santa_marta', label: 'Santa Marta' },
  { id: 'sincelejo', label: 'Sincelejo' },
  { id: 'tunja', label: 'Tunja' },
  { id: 'valledupar', label: 'Valledupar' },
  { id: 'villavicencio', label: 'Villavicencio' },
  { id: 'yopal', label: 'Yopal' },
  { id: 'other', label: 'Otra' },
];
