/** Ids de ciudad — 32 capitales departamentales + "Otra".
 *  Alineados con `companyCities.config.ts` en la webapp. */
export const COMPANY_CITY_IDS = [
  'arauca',
  'armenia',
  'barranquilla',
  'bogota',
  'bucaramanga',
  'cali',
  'cartagena',
  'cucuta',
  'florencia',
  'ibague',
  'inirida',
  'leticia',
  'manizales',
  'medellin',
  'mitu',
  'mocoa',
  'monteria',
  'neiva',
  'pasto',
  'pereira',
  'popayan',
  'puerto_carreno',
  'quibdo',
  'riohacha',
  'san_andres',
  'san_jose_del_guaviare',
  'santa_marta',
  'sincelejo',
  'tunja',
  'valledupar',
  'villavicencio',
  'yopal',
  'other',
] as const;
